spring:
  application:
    name: OrderManager
  jpa:
    generate-ddl: true
    show-sql: true
    
management:
  security:
    enabled: false
        
logging:
  level:
    io:
      pivotal:
        om: DEBUG
        